FROM mysql:8.0

ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes
ENV MYSQL_DATABASE=todo_app

# Copy database files
COPY database/schema.sql /docker-entrypoint-initdb.d/1-schema.sql
COPY database/seeds.sql /docker-entrypoint-initdb.d/2-seeds.sql
COPY database/indexes.sql /docker-entrypoint-initdb.d/3-indexes.sql

EXPOSE 3306
